# Site settings
title: TEDxNMIMSShirpur
description: |
  Coming Soon in 2018
  |
  NMIMS, Shirpur
owner: TEDxNMIMSShirpur
first_published: 2016 # if migrating another site, the year of your first publish
email: tedxnmimsshirpur@gmail.com
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://thatothertemp.github.io" # the base hostname & protocol for your site
social:
  #twitter: https://twitter.com/<username>
  #linkedin-square: https://linkedin.com/in/<username>
  facebook-official: https://facebook.com/<username>
  #google-plus-square: https://plus.google.com/u/0/+<username>
  email: /contact/
  flickr: flickr.com
  #instagram:
  youtube-square: youtube.com
  #spotify:
  #stack-overflow:
  #vimeo:
  #reddit:
  #stubleupon:
  #delicious:
  #pied-piper:
  #digg:
  #soundcloud:
  #deviantart:
  #angellist:
  #tumblr-square:
  #stackexchange:
  #weibo:
  #trello:
  #foursquare:
  #linux:
  #bitbucket-square:
  #vk:
  #slack:
  #vine:
  #weixin:
  #yelp:
  #skyatlas:
  #leanpub:
  #connectdevelop:
  #ils:
  #forumbee:
  #tripadvisor:
  #amazon:

# Build settings
markdown: kramdown
#sass:
#  style: compressed
